FROM node:20-alpine AS builder
RUN npm install --global eslint prettier

# WORKDIR /app
# COPY . .
# RUN npm ci
# RUN npm run build

# FROM nginx
# COPY --from=builder /app/build /usr/share/nginx/html